# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewCamera360' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewCamera360
pod "CTPanoramaView", "~> 1.5"
pod 'Image360', '~> 1.1.5'

end
